import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export type ScanResult = {
  id: string;
  extracted_text: string;
  confidence: number;
  recognition_quality: string;
  patient_name?: string | null;
  doctor_name?: string | null;
  date?: string | null;
  engines: Array<{ name: string; confidence: number }>;
  detected: Array<{
    raw: string;
    suggested?: string | null;
    match_method: string;
    match_score: number;
    matched_medicine: {
      name: string;
      generic: string | null;
      drug_class: string | null;
      indications: string | null;
      dosage: string | null;
      side_effects: string | null;
      manufacturer: string | null;
    } | null;
  }>;
  processing_time_ms: number;
};

const PRIMARY: [number, number, number] = [16, 122, 138]; // teal
const MUTED: [number, number, number] = [110, 116, 125];
const DARK: [number, number, number] = [25, 32, 45];

function confidenceStatus(c: number): "High" | "Medium" | "Low" {
  if (c >= 0.85) return "High";
  if (c >= 0.65) return "Medium";
  return "Low";
}

function aiSummary(result: ScanResult): string {
  const total = result.detected.length;
  const verified = result.detected.filter((d) => d.matched_medicine).length;
  const unknown = total - verified;
  const acc = Math.round(result.confidence * 100);
  return `Prescription processed successfully. ${total} medicine${total === 1 ? "" : "s"} detected, ${verified} verified${unknown ? `, ${unknown} unknown` : ""}. Overall OCR confidence: ${acc}% (${confidenceStatus(result.confidence)}). ${unknown ? "Manual review recommended for unmatched items." : "No major issues identified."}`;
}

function clinicalAlerts(result: ScanResult): string[] {
  const alerts: string[] = [];
  const names = result.detected
    .map((d) => d.matched_medicine?.name?.toLowerCase())
    .filter(Boolean) as string[];
  const dupes = names.filter((n, i) => names.indexOf(n) !== i);
  if (dupes.length) alerts.push(`Duplicate medicine(s) detected: ${[...new Set(dupes)].join(", ")}.`);
  const unknowns = result.detected.filter((d) => !d.matched_medicine);
  if (unknowns.length) alerts.push(`${unknowns.length} medicine(s) could not be verified in the database.`);
  const lowConf = result.detected.filter((d) => d.matched_medicine && d.match_score < 0.75);
  if (lowConf.length) alerts.push(`Low-confidence matches for: ${lowConf.map((d) => d.matched_medicine!.name).join(", ")}.`);
  return alerts;
}

function header(doc: jsPDF, reportId: string) {
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, 210, 28, "F");
  // Logo mark (circle + cross)
  doc.setFillColor(255, 255, 255);
  doc.circle(20, 14, 6, "F");
  doc.setFillColor(...PRIMARY);
  doc.rect(17.5, 11, 5, 6, "F");
  doc.setFillColor(255, 255, 255);
  doc.rect(19, 12.5, 2, 3, "F");
  doc.rect(17.5, 13.5, 5, 1, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("MediScan AI", 30, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Prescription Analysis Report", 30, 19);

  doc.setFontSize(8);
  doc.text(`Report ID: ${reportId.slice(0, 8).toUpperCase()}`, 205, 13, { align: "right" });
  doc.text(`Generated: ${new Date().toLocaleString()}`, 205, 19, { align: "right" });
}

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(220, 224, 230);
    doc.line(15, 285, 195, 285);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by MediScan AI · For healthcare assistance and review purposes only.", 15, 290);
    doc.text(`Page ${i} of ${pages}`, 195, 290, { align: "right" });
  }
}

function sectionTitle(doc: jsPDF, y: number, n: number, title: string): number {
  doc.setFillColor(241, 245, 247);
  doc.rect(15, y - 5, 180, 8, "F");
  doc.setFillColor(...PRIMARY);
  doc.rect(15, y - 5, 2, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...DARK);
  doc.text(`SECTION ${n}  ·  ${title}`, 20, y);
  return y + 8;
}

function ensureSpace(doc: jsPDF, y: number, need: number): number {
  if (y + need > 278) {
    doc.addPage();
    return 38;
  }
  return y;
}

export async function generatePrescriptionPdf(
  result: ScanResult,
  imageDataUrl: string | null,
): Promise<jsPDF> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  header(doc, result.id);
  let y = 38;

  // Section 1: Image
  y = sectionTitle(doc, y, 1, "Uploaded Prescription");
  y += 2;
  if (imageDataUrl) {
    try {
      const fmt = imageDataUrl.includes("image/png") ? "PNG" : "JPEG";
      doc.addImage(imageDataUrl, fmt, 15, y, 180, 90, undefined, "FAST");
      y += 95;
    } catch {
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text("(Image could not be embedded)", 15, y + 5);
      y += 10;
    }
  } else {
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text("(No image available)", 15, y + 5);
    y += 10;
  }

  // Section 2: Extracted text
  y = ensureSpace(doc, y, 40);
  y = sectionTitle(doc, y, 2, "Extracted Prescription Text");
  y += 3;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  const meta: Array<[string, string]> = [
    ["Patient Name", result.patient_name || "—"],
    ["Doctor Name", result.doctor_name || "—"],
    ["Date", result.date || "—"],
  ];
  for (const [k, v] of meta) {
    doc.setFont("helvetica", "bold");
    doc.text(`${k}:`, 17, y);
    doc.setFont("helvetica", "normal");
    doc.text(v, 50, y);
    y += 5;
  }
  y += 2;
  doc.setFont("helvetica", "bold");
  doc.text("Full Extracted Text:", 17, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(result.extracted_text || "—", 175);
  y = ensureSpace(doc, y, lines.length * 4 + 4);
  doc.setFillColor(248, 250, 251);
  doc.rect(15, y - 3, 180, lines.length * 4 + 4, "F");
  doc.text(lines, 17, y + 1);
  y += lines.length * 4 + 5;

  // Section 3: Detected medicines table
  y = ensureSpace(doc, y, 40);
  y = sectionTitle(doc, y, 3, "Detected Medicines");
  autoTable(doc, {
    startY: y + 2,
    head: [["#", "Medicine Name", "Match Confidence", "Verification Status"]],
    body: result.detected.length
      ? result.detected.map((d, i) => [
          String(i + 1),
          d.matched_medicine?.name ?? d.suggested ?? d.raw,
          `${Math.round(d.match_score * 100)}%`,
          d.matched_medicine
            ? d.match_method === "exact"
              ? "Verified"
              : "Needs Review"
            : "Unknown",
        ])
      : [["—", "No medicines detected", "—", "—"]],
    headStyles: { fillColor: PRIMARY, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    margin: { left: 15, right: 15 },
  });
  // @ts-expect-error lastAutoTable injected by plugin
  y = doc.lastAutoTable.finalY + 6;

  // Section 4: Medicine info
  if (result.detected.some((d) => d.matched_medicine)) {
    y = ensureSpace(doc, y, 30);
    y = sectionTitle(doc, y, 4, "Medicine Information");
    y += 2;
    for (const d of result.detected) {
      const m = d.matched_medicine;
      if (!m) continue;
      y = ensureSpace(doc, y, 38);
      doc.setDrawColor(230, 234, 240);
      doc.setFillColor(252, 253, 254);
      doc.roundedRect(15, y, 180, 34, 2, 2, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...PRIMARY);
      doc.text(m.name, 19, y + 6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...DARK);
      const rows: Array<[string, string]> = [
        ["Generic", m.generic || "—"],
        ["Drug Class", m.drug_class || "—"],
        ["Uses", m.indications || "—"],
        ["Dosage", m.dosage || "—"],
        ["Side Effects", m.side_effects || "—"],
        ["Manufacturer", m.manufacturer || "—"],
      ];
      let ry = y + 12;
      for (const [k, v] of rows) {
        doc.setFont("helvetica", "bold");
        doc.text(`${k}:`, 19, ry);
        doc.setFont("helvetica", "normal");
        const wrapped = doc.splitTextToSize(v, 140);
        doc.text(wrapped[0] ?? "—", 45, ry);
        ry += 3.6;
      }
      y += 38;
    }
  }

  // Section 5: OCR analysis
  y = ensureSpace(doc, y, 40);
  y = sectionTitle(doc, y, 5, "OCR Analysis");
  autoTable(doc, {
    startY: y + 2,
    head: [["OCR Engine", "Confidence"]],
    body: result.engines.map((e) => [e.name, `${Math.round(e.confidence * 100)}%`]),
    headStyles: { fillColor: PRIMARY, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    margin: { left: 15, right: 15 },
  });
  // @ts-expect-error lastAutoTable
  y = doc.lastAutoTable.finalY + 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.text(
    `Overall OCR Accuracy: ${Math.round(result.confidence * 100)}%   ·   Confidence: ${confidenceStatus(result.confidence)}   ·   Quality: ${result.recognition_quality}`,
    15,
    y,
  );
  y += 6;

  // Section 6: Clinical alerts
  const alerts = clinicalAlerts(result);
  if (alerts.length) {
    y = ensureSpace(doc, y, 20 + alerts.length * 6);
    y = sectionTitle(doc, y, 6, "Clinical Alerts");
    y += 2;
    for (const a of alerts) {
      doc.setFillColor(254, 243, 199);
      const lns = doc.splitTextToSize(`Warning: ${a}`, 172);
      const h = lns.length * 4 + 4;
      doc.roundedRect(15, y, 180, h, 1.5, 1.5, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(120, 53, 15);
      doc.text(lns, 19, y + 5);
      y += h + 3;
    }
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Recommendation: Manual review recommended.", 15, y);
    y += 6;
  }

  // Section 8: AI Summary
  y = ensureSpace(doc, y, 30);
  y = sectionTitle(doc, y, 8, "AI Summary");
  y += 3;
  const sum = doc.splitTextToSize(aiSummary(result), 175);
  doc.setFillColor(236, 248, 250);
  doc.roundedRect(15, y - 2, 180, sum.length * 4 + 6, 2, 2, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.text(sum, 19, y + 3);
  y += sum.length * 4 + 8;

  // Section 9: Report summary
  y = ensureSpace(doc, y, 28);
  y = sectionTitle(doc, y, 9, "Report Summary");
  const total = result.detected.length;
  const verified = result.detected.filter((d) => d.matched_medicine).length;
  const unknown = total - verified;
  autoTable(doc, {
    startY: y + 2,
    body: [
      ["Total Medicines Detected", String(total)],
      ["Verified Medicines", String(verified)],
      ["Unknown Medicines", String(unknown)],
      ["OCR Accuracy", `${Math.round(result.confidence * 100)}%`],
    ],
    styles: { fontSize: 9 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 70 } },
    margin: { left: 15, right: 15 },
  });

  footer(doc);
  return doc;
}

export function downloadJson(name: string, data: unknown) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  triggerDownload(blob, name);
}

export function downloadCsv(name: string, result: ScanResult) {
  const rows = [
    ["#", "Raw", "Medicine Name", "Generic", "Drug Class", "Match Confidence", "Status"],
    ...result.detected.map((d, i) => [
      String(i + 1),
      d.raw,
      d.matched_medicine?.name ?? d.suggested ?? "",
      d.matched_medicine?.generic ?? "",
      d.matched_medicine?.drug_class ?? "",
      `${Math.round(d.match_score * 100)}%`,
      d.matched_medicine ? (d.match_method === "exact" ? "Verified" : "Needs Review") : "Unknown",
    ]),
  ];
  const csv = rows
    .map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(","))
    .join("\n");
  triggerDownload(new Blob([csv], { type: "text/csv" }), name);
}

function triggerDownload(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
